package imprint

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (v *Vault) writeNotes(dir string, recs []*Record) (int, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0, err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			return 0, err
		}
	}
	n := 0
	for _, r := range recs {
		if r.Status != StatusActive {
			continue
		}
		name := r.ID + ".md"
		if err := writeFileAtomic(filepath.Join(dir, name), []byte(noteMarkdown(r))); err != nil {
			return n, err
		}
		n++
	}
	return n, nil
}

func noteMarkdown(r *Record) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "id: %s\n", r.ID)
	b.WriteString("scope:\n")
	for _, s := range r.Scope {
		fmt.Fprintf(&b, "  - %s\n", s)
	}
	fmt.Fprintf(&b, "confidence: %.2f\n", r.Confidence)
	fmt.Fprintf(&b, "status: %s\n", r.Status)
	b.WriteString("---\n\n")
	fmt.Fprintf(&b, "# %s\n\n", r.Claim)
	b.WriteString("- supersedes: ")
	b.WriteString(wikiList(r.Supersedes))
	b.WriteString("\n- related: ")
	b.WriteString(wikiList(r.Related))
	b.WriteString("\n- conflicts_with: ")
	b.WriteString(wikiList(r.ConflictsWith))
	b.WriteString("\n")
	if len(r.EvidenceLog) > 0 {
		b.WriteString("\n## Evidence\n\n")
		for _, e := range r.EvidenceLog {
			fmt.Fprintf(&b, "- %s (%s): %s\n", e.At.UTC().Format("2006-01-02"), e.Kind, e.Text)
		}
	}
	if rel := relativeShard(r.Path); rel != "" {
		fmt.Fprintf(&b, "\nSource shard: `%s`\n", rel)
	}
	b.WriteString("\nDo not edit this file. The imprint CLI owns the vault.\n")
	return b.String()
}

func wikiList(ids []string) string {
	if len(ids) == 0 {
		return "(none)"
	}
	parts := make([]string, 0, len(ids))
	for _, id := range ids {
		id = strings.TrimSpace(id)
		if id == "" {
			continue
		}
		parts = append(parts, "[["+id+"]]")
	}
	if len(parts) == 0 {
		return "(none)"
	}
	return strings.Join(parts, " ")
}

func relativeShard(path string) string {
	if path == "" {
		return ""
	}
	return filepath.ToSlash(filepath.Join("..", filepath.Base(path)))
}
